export const generateVideos = (startIndex: number, count: number) => {
   const videoData = [
    {
      title: "Building a Full Stack App with Next.js 14",
      channel: "Code with Antonio",
      views: "1.2M views",
      timestamp: "2 days ago",
      duration: "2:15:30",
      thumbnail: "/placeholder.svg?height=202&width=360&text=Next.js+Tutorial",
    },
    {
      title: "React 18 New Features Explained",
      channel: "Fireship",
      views: "850K views",
      timestamp: "1 week ago",
      duration: "8:42",
      thumbnail: "/placeholder.svg?height=202&width=360&text=React+18",
    },
    {
      title: "CSS Grid vs Flexbox - Complete Guide 2024",
      channel: "Kevin Powell",
      views: "2.1M views",
      timestamp: "3 days ago",
      duration: "18:45",
      thumbnail: "/placeholder.svg?height=202&width=360&text=CSS+Guide",
    },
    {
      title: "JavaScript ES2024 New Features",
      channel: "JavaScript Mastery",
      views: "650K views",
      timestamp: "5 days ago",
      duration: "12:30",
      thumbnail: "/placeholder.svg?height=202&width=360&text=JavaScript+ES2024",
    },
    {
      title: "TypeScript for Beginners - Complete Course",
      channel: "Programming with Mosh",
      views: "1.8M views",
      timestamp: "1 week ago",
      duration: "3:25:00",
      thumbnail: "/placeholder.svg?height=202&width=360&text=TypeScript+Course",
    },
    {
      title: "Node.js Performance Optimization Tips",
      channel: "Traversy Media",
      views: "420K views",
      timestamp: "4 days ago",
      duration: "19:20",
      thumbnail:
        "/placeholder.svg?height=202&width=360&text=Node.js+Performance",
    },
    {
      title: "Building a Chat App with Socket.io",
      channel: "Web Dev Simplified",
      views: "890K views",
      timestamp: "6 days ago",
      duration: "45:12",
      thumbnail: "/placeholder.svg?height=202&width=360&text=Socket.io+Chat",
    },
    {
      title: "Docker Tutorial for Beginners",
      channel: "TechWorld with Nana",
      views: "1.5M views",
      timestamp: "2 weeks ago",
      duration: "1:22:30",
      thumbnail: "/placeholder.svg?height=202&width=360&text=Docker+Tutorial",
    },
    {
      title: "AWS Cloud Practitioner Certification",
      channel: "freeCodeCamp.org",
      views: "3.2M views",
      timestamp: "1 month ago",
      duration: "4:15:45",
      thumbnail: "/placeholder.svg?height=202&width=360&text=AWS+Certification",
    },
    {
      title: "Python Data Science Complete Course",
      channel: "Corey Schafer",
      views: "2.8M views",
      timestamp: "3 weeks ago",
      duration: "6:30:20",
      thumbnail:
        "/placeholder.svg?height=202&width=360&text=Python+Data+Science",
    },
    {
      title: "Machine Learning Explained Simply",
      channel: "3Blue1Brown",
      views: "4.1M views",
      timestamp: "2 months ago",
      duration: "22:15",
      thumbnail: "/placeholder.svg?height=202&width=360&text=Machine+Learning",
    },
    {
      title: "Git and GitHub Tutorial for Beginners",
      channel: "The Net Ninja",
      views: "1.9M views",
      timestamp: "1 month ago",
      duration: "1:15:30",
      thumbnail: "/placeholder.svg?height=202&width=360&text=Git+GitHub",
    },
    {
      title: "Database Design Fundamentals",
      channel: "Database Star",
      views: "750K views",
      timestamp: "2 weeks ago",
      duration: "35:45",
      thumbnail: "/placeholder.svg?height=202&width=360&text=Database+Design",
    },
    {
      title: "API Development with Express.js",
      channel: "Academind",
      views: "1.1M views",
      timestamp: "1 week ago",
      duration: "2:45:20",
      thumbnail: "/placeholder.svg?height=202&width=360&text=Express.js+API",
    },
    {
      title: "Mobile App Development with React Native",
      channel: "Expo",
      views: "680K views",
      timestamp: "5 days ago",
      duration: "1:55:10",
      thumbnail: "/placeholder.svg?height=202&width=360&text=React+Native",
    },
    {
      title: "Cybersecurity Fundamentals 2024",
      channel: "Professor Messer",
      views: "920K views",
      timestamp: "1 week ago",
      duration: "3:10:45",
      thumbnail: "/placeholder.svg?height=202&width=360&text=Cybersecurity",
    },
    {
      title: "Blockchain Technology Explained",
      channel: "Simply Explained",
      views: "2.3M views",
      timestamp: "3 weeks ago",
      duration: "15:30",
      thumbnail: "/placeholder.svg?height=202&width=360&text=Blockchain",
    },
    {
      title: "Game Development with Unity",
      channel: "Brackeys",
      views: "1.7M views",
      timestamp: "2 months ago",
      duration: "2:20:15",
      thumbnail: "/placeholder.svg?height=202&width=360&text=Unity+Game+Dev",
    },
    {
      title: "3D Animation with Blender",
      channel: "Blender Guru",
      views: "3.5M views",
      timestamp: "1 month ago",
      duration: "4:45:30",
      thumbnail: "/placeholder.svg?height=202&width=360&text=Blender+Animation",
    },
    {
      title: "Digital Marketing Strategy 2024",
      channel: "Neil Patel",
      views: "1.3M views",
      timestamp: "2 weeks ago",
      duration: "1:35:20",
      thumbnail: "/placeholder.svg?height=202&width=360&text=Digital+Marketing",
    },
  ];

  return Array.from({ length: count }, (_, i) => {
    const index = (startIndex + i) % videoData.length;
    const video = videoData[index];
    return {
      id: `video-${startIndex + i}`,
      ...video,
      // Add some variation to make videos seem different
      views: `${Math.floor(Math.random() * 5000 + 100)}K views`,
      timestamp: `${Math.floor(Math.random() * 30 + 1)} days ago`,
    };
  });
};
