export const cars = [
  {
    id: 1,
    name: "Tesla Model S",
    category: "Luxury",
    image:
      "https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=400&h=250&fit=crop&auto=format&q=80",
    rating: 4.9,
    reviews: 127,
    price: 89,
    originalPrice: 99,
    features: {
      passengers: 5,
      fuel: "Electric",
      transmission: "Auto",
    },
    isPopular: true,
    isFavorite: false,
    available: true,
    description: "Premium electric luxury sedan with cutting-edge technology",
    location: "Downtown",
  },
  {
    id: 2,
    name: "BMW X5",
    category: "SUV",
    image:
      "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=400&h=250&fit=crop&auto=format&q=80",
    rating: 4.8,
    reviews: 89,
    price: 75,
    originalPrice: null,
    features: {
      passengers: 7,
      fuel: "Gasoline",
      transmission: "Auto",
    },
    isPopular: false,
    isFavorite: true,
    available: true,
    description: "Spacious luxury SUV perfect for family trips",
    location: "Airport",
  },
  {
    id: 3,
    name: "Audi A4",
    category: "Sedan",
    image:
      "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=400&h=250&fit=crop&auto=format&q=80",
    rating: 4.7,
    reviews: 156,
    price: 55,
    originalPrice: 65,
    features: {
      passengers: 5,
      fuel: "Gasoline",
      transmission: "Auto",
    },
    isPopular: false,
    isFavorite: false,
    available: true,
    description: "Elegant sedan with premium features and comfort",
    location: "Mall",
  },
  {
    id: 4,
    name: "Mercedes C-Class",
    category: "Luxury",
    image:
      "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=400&h=250&fit=crop&auto=format&q=80",
    rating: 4.9,
    reviews: 203,
    price: 79,
    originalPrice: null,
    features: {
      passengers: 5,
      fuel: "Gasoline",
      transmission: "Auto",
    },
    isPopular: true,
    isFavorite: false,
    available: true,
    description: "Sophisticated luxury sedan with premium amenities",
    location: "Downtown",
  },
  {
    id: 5,
    name: "Toyota Camry",
    category: "Economy",
    image:
      "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=400&h=250&fit=crop&auto=format&q=80",
    rating: 4.6,
    reviews: 95,
    price: 39,
    originalPrice: 49,
    features: {
      passengers: 5,
      fuel: "Gasoline",
      transmission: "Auto",
    },
    isPopular: false,
    isFavorite: true,
    available: false,
    description: "Reliable and fuel-efficient sedan for everyday use",
    location: "Airport",
  },
  {
    id: 6,
    name: "Porsche 911",
    category: "Sports",
    image: "/placeholder.svg",
    rating: 5.0,
    reviews: 67,
    price: 149,
    originalPrice: null,
    features: {
      passengers: 2,
      fuel: "Gasoline",
      transmission: "Manual",
    },
    isPopular: true,
    isFavorite: false,
    available: true,
    description: "Iconic sports car for the ultimate driving experience",
    location: "Downtown",
  },
  {
    id: 7,
    name: "Honda CR-V",
    category: "SUV",
    image:
      "https://images.unsplash.com/photo-1493238792000-8113da705763?w=400&h=250&fit=crop&auto=format&q=80",
    rating: 4.5,
    reviews: 134,
    price: 59,
    originalPrice: null,
    features: {
      passengers: 5,
      fuel: "Gasoline",
      transmission: "Auto",
    },
    isPopular: false,
    isFavorite: false,
    available: true,
    description: "Compact SUV with excellent fuel economy and reliability",
    location: "Mall",
  },
  {
    id: 8,
    name: "Ford Mustang",
    category: "Sports",
    image:
      "https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=400&h=250&fit=crop&auto=format&q=80",
    rating: 4.7,
    reviews: 89,
    price: 85,
    originalPrice: 95,
    features: {
      passengers: 4,
      fuel: "Gasoline",
      transmission: "Manual",
    },
    isPopular: false,
    isFavorite: true,
    available: true,
    description: "Classic American muscle car with powerful performance",
    location: "Downtown",
  },
];


  export const categories = ["All", "Economy", "Sedan", "SUV", "Luxury", "Sports"];
  export const locations = ["All", "Downtown", "Airport", "Mall"];
  export const priceRanges = [
    "All",
    "Under $50",
    "$50 - $80",
    "$80 - $120",
    "Over $120",
  ];