// Mock car data - in a real app, this would come from an API
export const carsData = {
  1: {
    id: 1,
    name: "Tesla Model S",
    category: "Luxury",
    images: [
      "https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=400&h=250&fit=crop&auto=format&q=80",
      "https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=400&h=250&fit=crop&auto=format&q=80",
      "https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=400&h=250&fit=crop&auto=format&q=80",
      "https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=400&h=250&fit=crop&auto=format&q=80",
    ],
    rating: 4.9,
    reviews: 127,
    price: 89,
    originalPrice: 99,
    features: {
      passengers: 5,
      fuel: "Electric",
      transmission: "Auto",
      doors: 4,
      bags: 3,
      airConditioning: true,
      bluetooth: true,
      gps: true,
      sunroof: true,
    },
    isPopular: true,
    available: true,
    description:
      "Experience the future of driving with the Tesla Model S. This premium electric luxury sedan combines cutting-edge technology, exceptional performance, and environmental consciousness in one remarkable package.",
    fullDescription:
      "The Tesla Model S represents the pinnacle of electric vehicle innovation. With its sleek design, spacious interior, and advanced autopilot features, this luxury sedan delivers an unparalleled driving experience. The dual motor all-wheel drive provides instant torque and exceptional handling, while the premium interior features high-quality materials and state-of-the-art technology including a 17-inch touchscreen display.",
    location: "Downtown",
    specifications: {
      make: "Tesla",
      model: "Model S",
      year: 2023,
      color: "Pearl White",
      engineSize: "Electric",
      fuelType: "Electric",
      mileage: "405 miles range",
      transmission: "Single-Speed Automatic",
      drivetrain: "All-Wheel Drive",
    },
    included: [
      "Comprehensive insurance",
      "24/7 roadside assistance",
      "Unlimited mileage",
      "GPS navigation system",
      "Bluetooth connectivity",
      "Air conditioning",
      "Premium sound system",
      "Mobile charging cables",
    ],
    pickupLocations: ["Downtown Main", "Airport Terminal", "Mall Parking"],
  },
};
