import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <h1 className="bg-black text-white text-center text-lg py-2">
          The original site :{" "}
          <Link
            className="text-blue-400 underline px-2"
            href=" https://www.governorsindh.com"
            target="blank"
          >
            The Governorsindh Kamran Khan Tessori
          </Link>
        </h1>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
