import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { TodoProvider } from "@/context/TodoContext";
import { UserProvider } from "@/context/UserProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <TodoProvider>
        <UserProvider>
          <body className={inter.className}>{children}</body>
        </UserProvider>
      </TodoProvider>
    </html>
  );
}
