// import { IProduct } from "./Types";

// export const products: IProduct[] = [
//   {
//     id: 1,
//     title: "Deluxe Chocolate Cake",
//     image: ["/images/cake1.jpg", "/images/cake1-side.jpg"],
//     slug: "deluxe-chocolate-cake",
//     price: 25.99,
//     category: "Cakes",
//     description:
//       "A rich and moist chocolate cake topped with creamy chocolate frosting.",
//     flavors: ["Chocolate", "Vanilla"],
//     topping: ["Choco Chips", "Whipped Cream"],
//     quantity: 1,
//     discount: 10,
//     Reviews: ["Best chocolate cake ever!", "My kids loved it."],
//     Rating: 4.5,
//     availability: true,
//   },
//   {
//     id: 2,
//     title: "Strawberry Shortcake",
//     image: "/images/strawberry_shortcake.jpg",
//     slug: "strawberry-shortcake",
//     price: 18.99,
//     category: "Cakes",
//     description:
//       "Light and fluffy cake layered with fresh strawberries and whipped cream.",
//     flavors: [],
//     topping: ["Fresh Strawberries"],
//     quantity: 1,
//     discount: "15%",
//     Reviews: ["Perfect for summer picnics!"],
//     Rating: 4.8,
//     availability: true,
//   },
//   {
//     id: 3,
//     title: "Assorted Donuts",
//     image: ["/images/donut1.jpg", "/images/donut2.jpg"],
//     slug: "assorted-donuts",
//     price: 12.99,
//     category: "Pastries",
//     description:
//       "A dozen assorted donuts with a mix of chocolate, glaze, and sprinkles.",
//     flavors: ["Chocolate", "Vanilla", "Strawberry"],
//     topping: ["Sprinkles", "Chocolate Drizzle", "Glaze"],
//     quantity: 1,
//     discount: "No Discount",
//     Reviews: ["Very fresh and tasty!", "Would buy again."],
//     Rating: 4.5,
//     availability: false,
//   },
//   {
//     id: 4,
//     title: "Lemon Tart",
//     image: "/images/lemon_tart.jpg",
//     slug: "lemon-tart",
//     price: 9.99,
//     category: "Pastries",
//     description:
//       "Tangy lemon curd on a buttery crust, topped with whipped cream.",
//     flavors: ["Lemon"],
//     topping: ["Whipped Cream"],
//     quantity: 1,
//     discount: 5,
//     Reviews: "The perfect balance of sweet and tart.",
//     Rating: 4.6,
//     availability: true,
//   },
//   {
//     id: 5,
//     title: "Triple Berry Pie",
//     image: "/images/berry_pie.jpg",
//     slug: "triple-berry-pie",
//     price: 19.99,
//     category: "Pies",
//     description:
//       "A mix of blueberries, raspberries, and blackberries in a flaky crust.",
//     flavors: ["Berry"],
//     topping: ["Powdered Sugar"],
//     quantity: 1,
//     discount: "20%",
//     Reviews: ["Fresh and delicious!", "Great for family gatherings."],
//     Rating: 4.9,
//     availability: true,
//   },
//   {
//     id: 6,
//     title: "Classic Croissant",
//     image: "/images/croissant.jpg",
//     slug: "classic-croissant",
//     price: 3.49,
//     category: "Pastries",
//     description: "Flaky and buttery croissant, perfect with coffee.",
//     flavors: ["Butter"],
//     topping: [],
//     quantity: 1,
//     discount: "No Discount",
//     Reviews: "Crispy and soft in all the right places.",
//     Rating: 4.7,
//     availability: true,
//   },
//   {
//     id: 7,
//     title: "Blueberry Muffin",
//     image: "/images/blueberry_muffin.jpg",
//     slug: "blueberry-muffin",
//     price: 2.99,
//     category: "Muffins",
//     description: "Soft muffin loaded with fresh blueberries.",
//     flavors: ["Blueberry"],
//     topping: ["Sugar Crystals"],
//     quantity: 1,
//     discount: 5,
//     Reviews: ["Best muffin ever!", "Always fresh and tasty."],
//     Rating: 4.8,
//     availability: true,
//   },
//   {
//     id: 8,
//     title: "Cinnamon Roll",
//     image: "/images/cinnamon_roll.jpg",
//     slug: "cinnamon-roll",
//     price: 4.99,
//     category: "Pastries",
//     description: "Warm cinnamon roll drizzled with vanilla icing.",
//     flavors: ["Cinnamon"],
//     topping: ["Icing"],
//     quantity: 1,
//     discount: 10,
//     Reviews: ["Sweet and soft, perfect for breakfast."],
//     Rating: 4.6,
//     availability: true,
//   },
//   {
//     id: 9,
//     title: "Carrot Cake",
//     image: "/images/carrot_cake.jpg",
//     slug: "carrot-cake",
//     price: 15.99,
//     category: "Cakes",
//     description: "Moist carrot cake with a layer of cream cheese frosting.",
//     flavors: ["Carrot"],
//     topping: ["Cream Cheese Frosting"],
//     quantity: 1,
//     discount: "15%",
//     Reviews: ["Tastes like homemade!", "A hit at every party."],
//     Rating: 4.7,
//     availability: true,
//   },
//   {
//     id: 10,
//     title: "Chocolate Chip Cookies",
//     image: "/images/chocolate_chip_cookies.jpg",
//     slug: "chocolate-chip-cookies",
//     price: 6.99,
//     category: "Cookies",
//     description: "Chewy cookies packed with chocolate chips.",
//     flavors: ["Chocolate"],
//     topping: [],
//     quantity: 1,
//     discount: 0,
//     Reviews: ["Best cookies in town!", "My kids love them."],
//     Rating: 4.9,
//     availability: true,
//   },
//   {
//     id: 11,
//     title: "Red Velvet Cupcakes",
//     image: "/images/red_velvet_cupcake.jpg",
//     slug: "red-velvet-cupcakes",
//     price: 14.99,
//     category: "Cupcakes",
//     description: "Rich red velvet cupcakes with cream cheese frosting.",
//     flavors: "Red Velvet",
//     topping: ["Cream Cheese Frosting"],
//     quantity: 1,
//     discount: "20%",
//     Reviews: ["Absolutely delicious!", "Perfect for celebrations."],
//     Rating: 4.8,
//     availability: true,
//   },
//   {
//     id: 12,
//     title: "Vanilla Ice Cream",
//     image: "/images/vanilla_ice_cream.jpg",
//     slug: "vanilla-ice-cream",
//     price: 4.99,
//     category: "Ice Cream",
//     description: "Creamy and smooth vanilla ice cream.",
//     flavors: ["Vanilla"],
//     topping: [],
//     quantity: 1,
//     discount: "No Discount",
//     Reviews: ["Classic and tasty."],
//     Rating: 4.5,
//     availability: true,
//   },
//   {
//     id: 13,
//     title: "Raspberry Macarons",
//     image: "/images/raspberry_macarons.jpg",
//     slug: "raspberry-macarons",
//     price: 8.99,
//     category: "Macarons",
//     description: "Delicate raspberry-flavored macarons.",
//     flavors: ["Raspberry"],
//     topping: [],
//     quantity: 1,
//     discount: 5,
//     Reviews: ["Perfectly sweet and crisp."],
//     Rating: 4.6,
//     availability: true,
//   },
//   {
//     id: 14,
//     title: "Mint Chocolate Chip Ice Cream",
//     image: "/images/mint_choco_ice_cream.jpg",
//     slug: "mint-chocolate-chip-ice-cream",
//     price: 5.99,
//     category: "Ice Cream",
//     description: "Cool mint ice cream with chocolate chips.",
//     flavors: ["Mint", "Chocolate"],
//     topping: [],
//     quantity: 1,
//     discount: 0,
//     Reviews: "The best summer treat!",
//     Rating: 4.8,
//     availability: true,
//   },
//   {
//     id: 15,
//     title: "Cheesecake",
//     image: "/images/cheesecake.jpg",
//     slug: "cheesecake",
//     price: 19.99,
//     category: "Cakes",
//     description: "Creamy cheesecake with a graham cracker crust.",
//     flavors: "Cheesecake",
//     topping: ["Berry Sauce"],
//     quantity: 1,
//     discount: "15%",
//     Reviews: ["Best cheesecake ever!", "Rich and creamy."],
//     Rating: 4.9,
//     availability: true,
//   },
//   {
//     id: 16,
//     title: "Chocolate Eclairs",
//     image: "/images/chocolate_eclairs.jpg",
//     slug: "chocolate-eclairs",
//     price: 7.99,
//     category: "Pastries",
//     description: "Pastries filled with cream and topped with chocolate icing.",
//     flavors: ["Chocolate", "Vanilla"],
//     topping: ["Chocolate Icing"],
//     quantity: 1,
//     discount: 10,
//     Reviews: ["Crispy and creamy."],
//     Rating: 4.7,
//     availability: true,
//   },
//   {
//     id: 17,
//     title: "Apple Pie",
//     image: "/images/apple_pie.jpg",
//     slug: "apple-pie",
//     price: 15.99,
//     category: "Pies",
//     description: "Traditional apple pie with a flaky crust.",
//     flavors: ["Apple"],
//     topping: ["Cinnamon Sugar"],
//     quantity: 1,
//     discount: 5,
//     Reviews: ["Perfectly sweet and spiced."],
//     Rating: 4.8,
//     availability: true,
//   },
//   {
//     id: 18,
//     title: "Pineapple Upside Down Cake",
//     image: "/images/pineapple_cake.jpg",
//     slug: "pineapple-upside-down-cake",
//     price: 16.99,
//     category: "Cakes",
//     description: "Moist cake with caramelized pineapple topping.",
//     flavors: "Pineapple",
//     topping: ["Caramelized Pineapple"],
//     quantity: 1,
//     discount: "10%",
//     Reviews: ["Delicious and unique."],
//     Rating: 4.7,
//     availability: true,
//   },
//   {
//     id: 19,
//     title: "Peanut Butter Cookies",
//     image: "/images/peanut_butter_cookies.jpg",
//     slug: "peanut-butter-cookies",
//     price: 5.99,
//     category: "Cookies",
//     description: "Soft cookies with a rich peanut butter flavor.",
//     flavors: "Peanut Butter",
//     topping: [],
//     quantity: 1,
//     discount: 0,
//     Reviews: ["Perfect for peanut butter lovers!"],
//     Rating: 4.6,
//     availability: true,
//   },
//   {
//     id: 20,
//     title: "Tiramisu",
//     image: "/images/tiramisu.jpg",
//     slug: "tiramisu",
//     price: 17.99,
//     category: "Desserts",
//     description:
//       "Classic Italian dessert with layers of coffee-soaked ladyfingers and mascarpone.",
//     flavors: ["Coffee", "Mascarpone"],
//     topping: ["Cocoa Powder"],
//     quantity: 1,
//     discount: "20%",
//     Reviews: ["Rich and flavorful.", "Tastes authentic!"],
//     Rating: 4.9,
//     availability: true,
//   },
// ];
